package com.github.patlego.mvn;

import java.util.Map;

import org.apache.maven.AbstractMavenLifecycleParticipant;
import org.apache.maven.MavenExecutionException;
import org.apache.maven.execution.MavenSession;
import org.codehaus.plexus.component.annotations.Component;
import org.codehaus.plexus.component.annotations.Requirement;

import org.slf4j.Logger;


@Component(role = AbstractMavenLifecycleParticipant.class)
public class CodeArtifactParticipant extends AbstractMavenLifecycleParticipant {

    @Requirement
    private Logger logger;

    @Override
    public void afterProjectsRead(MavenSession session) throws MavenExecutionException {
        logger.info(String.format("%s - About to set the repository tag password to the appropriate value", Constants.EXT_NAME));
        
        session.getSettings().getServer("aftia-internal").setPassword("eyJ2ZXIiOjEsImlzdSI6MTYyNTc2NDY2NSwiZW5jIjoiQTEyOEdDTSIsInRhZyI6IkNKRE9mLXIzbjluMXcyNEc1aGtHR1EiLCJleHAiOjE2MjU4MDc4NjUsImFsZyI6IkExMjhHQ01LVyIsIml2Ijoia0s4c3I3ZFBKdWtOQTcydyJ9.LClB784aeRn_X2krMhTfZQ.Z_9TKwt9YHTCpNtW.hVhfmFni1IFkJb11yHT2JgZiEhMelz4yRXhT1L9turDw1qAM7S2bvxikckVBn7c1VeoxzFEgqDd6cVBwAgCp6seLAXUV_YiOUpkHUwmPlc1V3cPizpnm4Xsu94fQ0XWpuYgH6PA9YtxLlBrv7Rsj597rnRYYfD1vT9xZEjFoRbdXnnOdHCdr_MpoZIz8ihJNs1iB3HNZCujXe_gkJbIHTXzksOER_S0RvY9TX3W9ld2gmf7Sg8gI-x8_uvG6z0H0RfgRIQ91X6V7It9UV0W89OhWFMkQlvcpiUZcJWVTCziccfXwSx9pqsrsSaYprpPQmrWjbvyJEipJht67y96TZbxGx0rTNZQ4NXXK_2PjJKtcICJUyT1o3OtMLS3UFg2BoeqWj0o7LRfD645ao6IqVMkuDFSSm-WjuFdoClsvfpR-JFR-37EDn08YnCHSQ39TudJ0PGyBhW7kjs6Q5W1kqrbQvC_ApjKAh1ieGQytzWWcqwpICvjFIMapdUTow4EFSqHthpeDOuDzXz9ZhctTPl4casr4IiIiqymBL4AV3toLlthHhV15rr4n31rqkX9vtCxKtVtdwYx26cKbVZ-OKqedky77OqjPFJjwNbblxCwOyERIUegkEPLquTmB0QXz1r_zUv0NatUWPxcivwZLzrBLUIA9YlsA0YicfY4LaTchV0UHDVZhdr7S7lm0gaA-cDKIdr_ogOaIoULRUmc6W4DMz3OS-83Brdqb0TCa0jBr7mwJKpGaoAkXGvESkrTS56xJDiFUpW1igSBCV5BnWHeLcyfI2CcXET52gQaz-nn25toFbLf0LPGvxKjuIROUjiEoVimgSfUKV4bN7PFyMIZTRecVnYnpkSbNFOeLIDC-CAKI3YSfMDq_AFr9KApTIPhbMdQaETEB-Ly4bKQO1y9v4tCygDzVJBYjSuFKJ8abPDl04HYZxHoFlg.Egt-tZ4azx2llEAKHPmvMA=");
        session.getSettings().getServer("aftia-internal").setPassphrase("eyJ2ZXIiOjEsImlzdSI6MTYyNTc2NDY2NSwiZW5jIjoiQTEyOEdDTSIsInRhZyI6IkNKRE9mLXIzbjluMXcyNEc1aGtHR1EiLCJleHAiOjE2MjU4MDc4NjUsImFsZyI6IkExMjhHQ01LVyIsIml2Ijoia0s4c3I3ZFBKdWtOQTcydyJ9.LClB784aeRn_X2krMhTfZQ.Z_9TKwt9YHTCpNtW.hVhfmFni1IFkJb11yHT2JgZiEhMelz4yRXhT1L9turDw1qAM7S2bvxikckVBn7c1VeoxzFEgqDd6cVBwAgCp6seLAXUV_YiOUpkHUwmPlc1V3cPizpnm4Xsu94fQ0XWpuYgH6PA9YtxLlBrv7Rsj597rnRYYfD1vT9xZEjFoRbdXnnOdHCdr_MpoZIz8ihJNs1iB3HNZCujXe_gkJbIHTXzksOER_S0RvY9TX3W9ld2gmf7Sg8gI-x8_uvG6z0H0RfgRIQ91X6V7It9UV0W89OhWFMkQlvcpiUZcJWVTCziccfXwSx9pqsrsSaYprpPQmrWjbvyJEipJht67y96TZbxGx0rTNZQ4NXXK_2PjJKtcICJUyT1o3OtMLS3UFg2BoeqWj0o7LRfD645ao6IqVMkuDFSSm-WjuFdoClsvfpR-JFR-37EDn08YnCHSQ39TudJ0PGyBhW7kjs6Q5W1kqrbQvC_ApjKAh1ieGQytzWWcqwpICvjFIMapdUTow4EFSqHthpeDOuDzXz9ZhctTPl4casr4IiIiqymBL4AV3toLlthHhV15rr4n31rqkX9vtCxKtVtdwYx26cKbVZ-OKqedky77OqjPFJjwNbblxCwOyERIUegkEPLquTmB0QXz1r_zUv0NatUWPxcivwZLzrBLUIA9YlsA0YicfY4LaTchV0UHDVZhdr7S7lm0gaA-cDKIdr_ogOaIoULRUmc6W4DMz3OS-83Brdqb0TCa0jBr7mwJKpGaoAkXGvESkrTS56xJDiFUpW1igSBCV5BnWHeLcyfI2CcXET52gQaz-nn25toFbLf0LPGvxKjuIROUjiEoVimgSfUKV4bN7PFyMIZTRecVnYnpkSbNFOeLIDC-CAKI3YSfMDq_AFr9KApTIPhbMdQaETEB-Ly4bKQO1y9v4tCygDzVJBYjSuFKJ8abPDl04HYZxHoFlg.Egt-tZ4azx2llEAKHPmvMA=");
        logger.info(session.getSettings().getServer("aftia-internal").getPassword());
        for (Map.Entry entry : session.getRepositorySession().getSystemProperties().entrySet()) {
            logger.info(entry.getKey() + " " + entry.getValue());
        }
        session.getRepositorySession().getSystemProperties().put("env.CODEARTIFACT_AUTH_TOKEN", "eyJ2ZXIiOjEsImlzdSI6MTYyNTc2NDY2NSwiZW5jIjoiQTEyOEdDTSIsInRhZyI6IkNKRE9mLXIzbjluMXcyNEc1aGtHR1EiLCJleHAiOjE2MjU4MDc4NjUsImFsZyI6IkExMjhHQ01LVyIsIml2Ijoia0s4c3I3ZFBKdWtOQTcydyJ9.LClB784aeRn_X2krMhTfZQ.Z_9TKwt9YHTCpNtW.hVhfmFni1IFkJb11yHT2JgZiEhMelz4yRXhT1L9turDw1qAM7S2bvxikckVBn7c1VeoxzFEgqDd6cVBwAgCp6seLAXUV_YiOUpkHUwmPlc1V3cPizpnm4Xsu94fQ0XWpuYgH6PA9YtxLlBrv7Rsj597rnRYYfD1vT9xZEjFoRbdXnnOdHCdr_MpoZIz8ihJNs1iB3HNZCujXe_gkJbIHTXzksOER_S0RvY9TX3W9ld2gmf7Sg8gI-x8_uvG6z0H0RfgRIQ91X6V7It9UV0W89OhWFMkQlvcpiUZcJWVTCziccfXwSx9pqsrsSaYprpPQmrWjbvyJEipJht67y96TZbxGx0rTNZQ4NXXK_2PjJKtcICJUyT1o3OtMLS3UFg2BoeqWj0o7LRfD645ao6IqVMkuDFSSm-WjuFdoClsvfpR-JFR-37EDn08YnCHSQ39TudJ0PGyBhW7kjs6Q5W1kqrbQvC_ApjKAh1ieGQytzWWcqwpICvjFIMapdUTow4EFSqHthpeDOuDzXz9ZhctTPl4casr4IiIiqymBL4AV3toLlthHhV15rr4n31rqkX9vtCxKtVtdwYx26cKbVZ-OKqedky77OqjPFJjwNbblxCwOyERIUegkEPLquTmB0QXz1r_zUv0NatUWPxcivwZLzrBLUIA9YlsA0YicfY4LaTchV0UHDVZhdr7S7lm0gaA-cDKIdr_ogOaIoULRUmc6W4DMz3OS-83Brdqb0TCa0jBr7mwJKpGaoAkXGvESkrTS56xJDiFUpW1igSBCV5BnWHeLcyfI2CcXET52gQaz-nn25toFbLf0LPGvxKjuIROUjiEoVimgSfUKV4bN7PFyMIZTRecVnYnpkSbNFOeLIDC-CAKI3YSfMDq_AFr9KApTIPhbMdQaETEB-Ly4bKQO1y9v4tCygDzVJBYjSuFKJ8abPDl04HYZxHoFlg.Egt-tZ4azx2llEAKHPmvMA=");
    }

    @Override
    public void afterSessionStart(MavenSession session) throws MavenExecutionException {
        // Do Nothing
    }
}
